CREATE
EXTENSION IF NOT EXISTS "uuid-ossp";

create table user_credential
(
    id       bigint generated by default as identity
        constraint user_credential_pkey
            primary key,
    password varchar(255),
    username varchar(255)
);

alter table user_credential
    owner to postgres;

create table authority
(
    id   bigint not null
        constraint authority_pkey
            primary key,
    name varchar(255)
);

alter table authority
    owner to postgres;

create table user_credential_authorities
(
    user_credential_id bigint not null
        constraint fk5qewxypaiahr0iur9cgf7dqbd
            references user_credential
            on delete cascade,
    authorities_id     bigint not null
        constraint fkj0iityoi0hmj8n7imu99o7ca8
            references authority,
    constraint user_credential_authorities_pkey
        primary key (user_credential_id, authorities_id)
);

alter table user_credential_authorities
    owner to postgres;

create table cam_female_model
(
    id            bigint  not null
        constraint cam_female_model_pkey
            primary key,
    age           integer not null,
    growth        integer not null,
    hair_color    varchar(255),
    is_active     boolean not null,
    male          varchar(255),
    popa_size     varchar(255),
    titi_size     varchar(255),
    credential_id bigint
        constraint fk95mjp3lklidbo0u5fvxpei271
            references user_credential
);

alter table cam_female_model
    owner to postgres;

INSERT INTO public.authority (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO public.authority (id, name) VALUES (2, 'ROLE_ADMIN');
INSERT INTO public.authority (id, name) VALUES (3, 'ROLE_MODEL');